"""empty message

Revision ID: 9a992ef15551
Revises: 61c03915d50b
Create Date: 2022-11-07 13:11:17.088383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a992ef15551'
down_revision = '61c03915d50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('restaurant_name', sa.String(), nullable=True))
    op.drop_column('menu', 'restaraunt_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('restaraunt_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('menu', 'restaurant_name')
    # ### end Alembic commands ###
