"""empty message

Revision ID: f64b829c230d
Revises: 2845fb15a599
Create Date: 2022-10-27 12:04:39.584268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64b829c230d'
down_revision = '2845fb15a599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breakfast', sa.Column('prep_time', sa.Integer(), nullable=True))
    op.drop_column('breakfast', 'prep_meal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breakfast', sa.Column('prep_meal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('breakfast', 'prep_time')
    # ### end Alembic commands ###
